# Generated by Django 4.2 on 2023-04-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasknote_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tasknote',
            name='author',
        ),
        migrations.AddField(
            model_name='tasknote',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
    ]
