# Generated by Django 4.2 on 2023-04-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasknote_options_tasknote_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created',)},
        ),
    ]
